/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import Dados.Dados;
import blackjack.BlackJack;
import PPT.ppt;

import java.awt.Graphics;
import java.awt.Image;
import static java.awt.SystemColor.menu;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author aazur
 */
public class Menu extends javax.swing.JFrame {

    private static UsuarioDAO usuarioDAO = new UsuarioDAO();
    private static int dinerousuario = 0;
    FondoPanel panel = new FondoPanel();
    private static String player;

    /**
     * Creates new form Menu
     */
    public Menu() {
        this.setContentPane(panel);
        initComponents();

    }
    public Menu(String user,int diner){
    dinerousuario=diner;
    player=user;
    initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        todo = new FondoPanel();
        black = new javax.swing.JLabel();
        ppt = new javax.swing.JLabel();
        dad = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        black.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/BJicono.png"))); // NOI18N
        black.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blackMouseClicked(evt);
            }
        });

        ppt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/iconopiedra.png"))); // NOI18N
        ppt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pptMouseClicked(evt);
            }
        });

        dad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/logodado.png"))); // NOI18N
        dad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dadMouseClicked(evt);
            }
        });

        cerrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cerrar.setForeground(new java.awt.Color(204, 0, 153));
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/close.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/mony2.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout todoLayout = new javax.swing.GroupLayout(todo);
        todo.setLayout(todoLayout);
        todoLayout.setHorizontalGroup(
            todoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todoLayout.createSequentialGroup()
                .addGroup(todoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(todoLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(black, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(ppt)
                        .addGap(157, 157, 157)
                        .addComponent(dad))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, todoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        todoLayout.setVerticalGroup(
            todoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(black, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, todoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(todoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 435, Short.MAX_VALUE)
                .addGroup(todoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dad, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, todoLayout.createSequentialGroup()
                        .addComponent(ppt)
                        .addGap(50, 50, 50))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(todo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(todo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void blackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blackMouseClicked
        // TODO add your handling code here:
        BlackJack black = new BlackJack(player,dinerousuario);

        black.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_blackMouseClicked

    private void pptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pptMouseClicked
        // TODO add your handling code here:
        ppt piedra = new ppt(player, dinerousuario);

        piedra.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pptMouseClicked

    private void dadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dadMouseClicked
        // TODO add your handling code here:
        Dados dado = new Dados(player, dinerousuario);

        dado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dadMouseClicked

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "¿ESTAS SEGURO?", "SALIR", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_cerrarMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Tu saldo es de $"+dinerousuario);
    }//GEN-LAST:event_jLabel2MouseClicked
    private static void iniciarSesion() {
        String usuario = JOptionPane.showInputDialog(null, "Introduce tu usuario:", "Inicio de sesión", JOptionPane.QUESTION_MESSAGE);
        if (usuario == null) {
            System.exit(0);
            return;
        }
        player = usuario;
        String contraseña = JOptionPane.showInputDialog(null, "Introduce tu contraseña:", "Inicio de sesión", JOptionPane.QUESTION_MESSAGE);
        if (contraseña == null) {
            System.exit(0);
            return;
        }

        Usuario user = usuarioDAO.iniciarSesion(usuario, contraseña);
        if (user != null) {
            dinerousuario = user.getDinero();

            JOptionPane.showMessageDialog(null, "Bienvenido, " + usuario + "! \nDinero disponible: $" + dinerousuario, "Sesión iniciada", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos.", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }

    private static void crearUsuario() {
        String usuario = JOptionPane.showInputDialog(null, "Elige un nombre de usuario:", "Crear usuario", JOptionPane.QUESTION_MESSAGE);
        if (usuario == null || usuario.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El nombre de usuario no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
            return;
        }

        String contraseña = JOptionPane.showInputDialog(null, "Elige una contraseña:", "Crear usuario", JOptionPane.QUESTION_MESSAGE);
        if (contraseña == null || contraseña.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "La contraseña no puede estar vacía.", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
            return;
        }

        String dineroStr = JOptionPane.showInputDialog(null, "Introduce la cantidad de dinero inicial:", "Crear usuario", JOptionPane.QUESTION_MESSAGE);
        if (dineroStr == null || dineroStr.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un valor numérico para el dinero inicial.", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
            return;
        }

        try {
            int dinero = Integer.parseInt(dineroStr);
            if (dinero < 0) {
                JOptionPane.showMessageDialog(null, "El dinero inicial no puede ser negativo.", "Error", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
                return;
            }

            Usuario newUser = new Usuario(usuario, contraseña, dinero);
            boolean creado = usuarioDAO.crearUsuario(newUser); // Verifica si el usuario se creó correctamente

            if (creado) {
                dinerousuario = dinero;
                player = usuario;
                JOptionPane.showMessageDialog(null, "Usuario creado con éxito. Bienvenido, " + usuario + "!", "Usuario creado", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "El usuario ya existe. Intenta con otro nombre.", "Error", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un número válido para el dinero.", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }

    public void mostrarOpcionesInicio() {
        JOptionPane.showMessageDialog(this, "¡Bienvenido al juego de Blackjack!", "Bienvenida", JOptionPane.INFORMATION_MESSAGE);

        String[] opciones = {"Iniciar sesión", "Crear usuario"};
        int seleccion = JOptionPane.showOptionDialog(
                this,
                "Selecciona una opción para continuar:",
                "Menú",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                opciones[0]
        );

        if (seleccion == 0) {
            iniciarSesion();
        } else if (seleccion == 1) {
            crearUsuario();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu menu = new Menu(); // Crear la instancia del menú
                menu.setVisible(true);  // Mostrar la ventana principal
                menu.mostrarOpcionesInicio(); // Llamar a un método para las opciones

            }
        });

    }

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Menu/fondomenu.png")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel black;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel dad;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel ppt;
    private javax.swing.JPanel todo;
    // End of variables declaration//GEN-END:variables
}
