/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dados;


import Menu.Menu;
import java.awt.Graphics;
import java.awt.Image;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author aazur
 */
public class Dados extends javax.swing.JFrame {
    FondoPanel panel = new FondoPanel();
    Random rd = new Random();
    int sumajugador = 0;
    int sumamaquina = 0;
    private ImageIcon[] dados;


    /**
     * Creates new form Dados
     */
    public Dados( String usuario,int dinero){
    this.setContentPane(panel);
    initComponents();
        if (usuario!=null) {
            lanzamiento1.setText("Lanzamiento "+usuario);
        }
    
    }
    public Dados() {
    this.setContentPane(panel);    
        this.dados = new ImageIcon[]{
            new ImageIcon(getClass().getResource("/Dados/dado1.png")),
            new ImageIcon(getClass().getResource("/Dados/dado2.png")),
            new ImageIcon(getClass().getResource("/Dados/dado3.png")),
            new ImageIcon(getClass().getResource("/Dados/dado4.png")),
            new ImageIcon(getClass().getResource("/Dados/dado5.png")),
            new ImageIcon(getClass().getResource("/Dados/dado6.png"))
        };

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        dosdados = new javax.swing.JLabel();
        lanzamiento1 = new javax.swing.JLabel();
        lanzamiento2 = new javax.swing.JLabel();
        jugadordado = new javax.swing.JLabel();
        maquinadado = new javax.swing.JLabel();
        suma1 = new javax.swing.JLabel();
        suma2 = new javax.swing.JLabel();
        retroceder = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(153, 0, 153));
        titulo.setText("LA SUERTE DE LOS DADOS");

        dosdados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dados/pngegg (10).png"))); // NOI18N

        lanzamiento1.setForeground(new java.awt.Color(153, 0, 153));
        lanzamiento1.setText("Lanzamiento jugador");

        lanzamiento2.setForeground(new java.awt.Color(153, 0, 153));
        lanzamiento2.setText("Lanzamiento máquina");

        jugadordado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dados/dado.png"))); // NOI18N
        jugadordado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jugadordadoMouseClicked(evt);
            }
        });

        maquinadado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dados/dado.png"))); // NOI18N

        suma1.setForeground(new java.awt.Color(153, 0, 153));
        suma1.setText("Suma total:");

        suma2.setForeground(new java.awt.Color(153, 0, 153));
        suma2.setText("Suma total:");

        retroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dados/return.png"))); // NOI18N
        retroceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retrocederMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(suma1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jugadordado)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(lanzamiento1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addComponent(dosdados)
                        .addGap(37, 37, 37)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lanzamiento2)
                        .addGap(88, 88, 88))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(suma2)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(maquinadado)
                        .addGap(73, 73, 73))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(retroceder)
                .addGap(243, 243, 243)
                .addComponent(titulo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(retroceder)
                        .addGap(111, 111, 111)
                        .addComponent(lanzamiento1)
                        .addGap(55, 55, 55)
                        .addComponent(jugadordado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(lanzamiento2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(maquinadado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(titulo)
                        .addGap(61, 61, 61)
                        .addComponent(dosdados)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suma1)
                    .addComponent(suma2))
                .addContainerGap(340, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jugadordadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugadordadoMouseClicked
        // TODO add your handling code here:
        jugar();
    }//GEN-LAST:event_jugadordadoMouseClicked

    private void retrocederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retrocederMouseClicked
        // TODO add your handling code here:
            this.setVisible(false); // Oculta la ventana actual
    new Menu().setVisible(true); // Crea y muestra el menú principal con el dinero actual
    this.dispose(); // Libera los recursos de la ventana actual


    }//GEN-LAST:event_retrocederMouseClicked
    public void jugar() {
        int dadoJugador = rd.nextInt(6);
        int dadoMaquina = rd.nextInt(6);

        sumajugador = sumajugador + dadoJugador;
        sumamaquina = sumamaquina + dadoMaquina;

        suma1.setText("Suma total: " + sumajugador);
        suma2.setText("Suma total: " + sumamaquina);

        actualizarDado(jugadordado, dadoJugador);
        actualizarDado(maquinadado, dadoMaquina);
        if (sumajugador >= 20 & sumamaquina < sumajugador) {
            JOptionPane.showMessageDialog(this, "Ha ganado el jugador!");
            acabar();
        }
        if (sumamaquina >= 20 & sumamaquina > sumajugador) {
            JOptionPane.showMessageDialog(this, "Ganó la máquina!");
            acabar();
        }
        }

    private void actualizarDado(JLabel label, int dado) {
        label.setIcon(dados[dado]); // Se usa el array directamente

    }
    private void acabar(){
        int opcion=JOptionPane.showConfirmDialog(this, "Volver a jugar","Continuar",JOptionPane.YES_NO_OPTION);
        if (opcion==JOptionPane.YES_OPTION) {
            suma1.setText("Suma total: ");
            suma2.setText("Suma total: ");
            sumajugador=0;
            sumamaquina=0;
            JOptionPane.showMessageDialog(this, "A disfrutar!");
        }else{
            JOptionPane.showMessageDialog(this, "Adios!");
            this.dispose();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dados().setVisible(true);
            }
        });
    }
    class FondoPanel extends JPanel {

    private Image imagen;

    @Override
    public void paint(Graphics g) {

        imagen = new ImageIcon(getClass().getResource("/Dados/fondodado.jpg")).getImage();
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

        setOpaque(false);

        super.paint(g);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dosdados;
    private javax.swing.JLabel jugadordado;
    private javax.swing.JLabel lanzamiento1;
    private javax.swing.JLabel lanzamiento2;
    private javax.swing.JLabel maquinadado;
    private javax.swing.JLabel retroceder;
    private javax.swing.JLabel suma1;
    private javax.swing.JLabel suma2;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
