
package PPT;

import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author aazur
 */

public class ppt extends javax.swing.JFrame {
    FondoPanel panel = new FondoPanel();
    int contJ = 0;
    int contM = 0;
    String nombreusuario;
    enum Resultado {
        Piedra,
        Papel,
        Tijera,
        Ninguna
    }
    Resultado operacion = Resultado.Ninguna;
    String jugador = "";
    Random rd = new Random(3);

    /**
     * Creates new form Parejas
     * @param usuario
     */
    public ppt(String usuario){
        
        this.setContentPane(panel);
        initComponents();
        player.setText(usuario);
    }
    public ppt() {
        this.setContentPane(panel);
        initComponents();
    }

    private void jugar(Resultado eleccionJugador) {
        Resultado[] posibilidades = Resultado.values();
        Resultado maquina = posibilidades[rd.nextInt(3)];

        // Cargar imágenes
        ImageIcon iconop = new ImageIcon(getClass().getResource("/PPT/piedra.png"));
        ImageIcon iconopap = new ImageIcon(getClass().getResource("/PPT/papel.png"));
        ImageIcon iconotij = new ImageIcon(getClass().getResource("/PPT/tijeras.png"));

        
        // Asignar imagen según la elección de la máquina
        switch (maquina) {
            case Piedra:
                eleccionmaquina.setIcon(iconop);
                break;
            case Papel:
                eleccionmaquina.setIcon(iconopap);
                break;
            case Tijera:
                eleccionmaquina.setIcon(iconotij);
                break;
        }

        // Determinar el resultado
        if (eleccionJugador == maquina) {
            resultado.setText("Empate");
        } else if ((eleccionJugador == Resultado.Piedra && maquina == Resultado.Tijera)
                || (eleccionJugador == Resultado.Papel && maquina == Resultado.Piedra)
                || (eleccionJugador == Resultado.Tijera && maquina == Resultado.Papel)) {
            resultado.setText("Gana Jugador");
            contJ++;
        } else {
            resultado.setText("Gana Máquina");
            contM++;
        }

        // Actualizar marcador
        victoriasjugador.setText("Victorias Jugador: " + contJ);
        victoriasmaquina.setText("Victorias Máquina: " + contM);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jugar = new javax.swing.JButton();
        papel = new javax.swing.JLabel();
        piedra = new javax.swing.JLabel();
        tijera = new javax.swing.JLabel();
        eleccionmaquina = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        player = new javax.swing.JLabel();
        maquina = new javax.swing.JLabel();
        victoriasjugador = new javax.swing.JLabel();
        victoriasmaquina = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jugar.setBackground(new java.awt.Color(153, 0, 153));
        jugar.setText("Jugar");
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });

        papel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PPT/papel.png"))); // NOI18N
        papel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                papelMouseClicked(evt);
            }
        });

        piedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PPT/piedra.png"))); // NOI18N
        piedra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                piedraMouseClicked(evt);
            }
        });

        tijera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PPT/tijeras.png"))); // NOI18N
        tijera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tijeraMouseClicked(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(153, 0, 153));
        titulo.setText("PIEDRA-PAPEL-TIJERA");

        player.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        player.setForeground(new java.awt.Color(153, 0, 153));
        player.setText("Jugador");

        maquina.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        maquina.setForeground(new java.awt.Color(153, 0, 153));
        maquina.setText("Máquina");

        victoriasjugador.setForeground(new java.awt.Color(153, 0, 153));
        victoriasjugador.setText("Victorias:");

        victoriasmaquina.setForeground(new java.awt.Color(153, 0, 153));
        victoriasmaquina.setText("Victorias:");

        resultado.setForeground(new java.awt.Color(153, 0, 153));
        resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultado.setText("Resultado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(piedra)
                    .addComponent(tijera)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(papel))
                    .addComponent(player)
                    .addComponent(victoriasjugador, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140)
                .addComponent(resultado, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addGap(169, 169, 169)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eleccionmaquina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maquina)
                    .addComponent(victoriasmaquina, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titulo)
                        .addGap(272, 272, 272))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jugar)
                        .addGap(368, 368, 368))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(player)
                            .addComponent(maquina))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(papel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(piedra)
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(eleccionmaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)))
                        .addComponent(tijera)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(victoriasjugador)
                                    .addComponent(victoriasmaquina))
                                .addGap(158, 158, 158))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jugar)
                                .addGap(29, 29, 29)
                                .addComponent(resultado)
                                .addGap(147, 147, 147))))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tijeraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tijeraMouseClicked
        // TODO add your handling code here:
        operacion = Resultado.Papel;
    }//GEN-LAST:event_tijeraMouseClicked

    private void piedraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piedraMouseClicked
        // TODO add your handling code here:
        operacion = Resultado.Piedra;
    }//GEN-LAST:event_piedraMouseClicked

    private void papelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_papelMouseClicked
        // TODO add your handling code here:
        operacion = Resultado.Papel;
    }//GEN-LAST:event_papelMouseClicked

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
        // TODO add your handling code here:
        if (operacion != Resultado.Ninguna) {
            jugar(operacion);
        } else {
            resultado.setText("Selecciona una opción antes de jugar");
        }

    }//GEN-LAST:event_jugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(ppt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(ppt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(ppt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(ppt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new ppt().setVisible(true);
        }
    });
}
    class FondoPanel extends JPanel {

    private Image imagen;

    @Override
    public void paint(Graphics g) {

        imagen = new ImageIcon(getClass().getResource("/PPT/fondoPPT.png")).getImage();
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

        setOpaque(false);

        super.paint(g);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eleccionmaquina;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jugar;
    private javax.swing.JLabel maquina;
    private javax.swing.JLabel papel;
    private javax.swing.JLabel piedra;
    private javax.swing.JLabel player;
    private javax.swing.JLabel resultado;
    private javax.swing.JLabel tijera;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField titulo1;
    private javax.swing.JTextField titulo2;
    private javax.swing.JTextField titulo3;
    private javax.swing.JLabel victoriasjugador;
    private javax.swing.JLabel victoriasmaquina;
    // End of variables declaration//GEN-END:variables
}
